import org.junit.Test;

import addams.family.gui.Library;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'developer' at '20/11/15 14:01' with Gradle 2.6
 *
 * @author developer, @date 20/11/15 14:01
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
      //  assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
